# Compile MESH on Windows Subsystem for Linux
# export variables are used in the makefile. 
startpath=$(pwd)
#---------------------------------
# Specify settings
#---------------------------------

# --- Location of source code
# Find the path to the source code in 'control_active.txt'
dest_line=$(grep -m 1 "^install_path_MESH" ../0_control_files/control_active.txt) # full settings line
MESH_path=$(echo ${dest_line##*|})   # removing the leading text up to '|'
MESH_path=$(echo ${MESH_path%%#*}) # removing the trailing comments, if any are present
echo Reading MESH Path: $MESH_path
# Specify the default path if needed
if [ "$MESH_path" = "default" ]; then
  
 # Get the root path and append the appropriate install directories
 root_line=$(grep -m 1 "^root_path" ../0_control_files/control_active.txt)
 root_path=$(echo ${root_line##*|}) 
 root_path=$(echo ${root_path%%#*}) 
 MESH_path="${root_path}/installs/MESH"
fi
echo Asigning MESH Path: $MESH_path

# Specify home directory of 'MESH/build'
export F_MASTER=$MESH_path

# --- Specify a name for the executable 
# Find the desired executable name in 'control_active.txt'
exe_line=$(grep -m 1 "^exe_name_MESH" ../0_control_files/control_active.txt) 
MESH_exe=$(echo ${exe_line##*|}) 
MESH_exe=$(echo ${MESH_exe%%#*}) 
export EXE_NAME=$MESH_exe

# --- Compiler settings 
# Compiler (ifort // gfortran)
export FC=gfortran

# Compiler .exe
export FC_EXE='gfortran'

# unzip standalone MESH zipped folder
unzip $MESH_path/r1813.zip -d $MESH_path
rm $MESH_path/r1813.zip

module load openmpi
module load netcdf-fortran

cd $MESH_path/r1813
echo $(pwd)

make netcdf

#---------------------------------
# Code provenance
#---------------------------------
# Generates a basic log file in the domain folder and copies the control file and itself there.
# Make a log directory if it doesn't exist
log_path="${MESH_path}/_workflow_log"
mkdir -p $log_path

# Log filename
today=`date '+%F'`
log_file="${today}_compile_log.txt"

# Make the log
this_file='1b_compile_MESH.sh'
echo "Log generated by ${this_file} on `date '+%F %H:%M:%S'`"  > $log_path/$log_file # 1st line, store in new file
echo 'Compiled MESH into parent directory' >> $log_path/$log_file # 2nd line, append to existing file

# Copy this file to log directory
cp $startpath/$this_file $log_path