      MODULE FLAGS

      INTEGER SOILINIFLAG
      INTEGER NRSOILAYEREADFLAG
!> DEC 31/18 - DGP NUDGESDEPFLAG
      integer :: NUDGESDEPFLAG = 0
      INTEGER RELFLG
      INTEGER SUBBASINFLAG
      INTEGER R2COUTPUTFLAG
      INTEGER OBJFNFLAG
      INTEGER WINDOWSIZEFLAG
      INTEGER WINDOWSPACINGFLAG
      INTEGER METRICSSTATSOUTFLAG
      INTEGER METRICSFILTEROBSFLAG
      INTEGER METRICSSPINUP
      INTEGER METRICSINCLUDESPINUP
      INTEGER FROZENSOILINFILFLAG
!> OCT 16/14 -GSA- GET Geothermal flux
      INTEGER GGEOFLAG

!-      integer :: BASINAVGEVPFILEFLAG = 0
!-      INTEGER :: BASINSWEOUTFLAG = 0
!> FEB 8/17 -GSA- Reservoir
      INTEGER RESERVOIRFLAG

      END
